# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o3evwV3NPff_310UnKSkqI6oUpe0aBMk
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("Mobile Reviews Sentiment.csv")

print("Rows and Columns:", data.shape)

data.head()

#check dataset information
print("Columns:")
print(data.columns)

print("\nData Types:")
print(data.dtypes)

print("\nMissing Values:")
print(data.isnull().sum())

print("\nDuplicate Rows:")
print(data.duplicated().sum())

sentiment_count = data["sentiment"].value_counts()

print(sentiment_count)

plt.figure(figsize=(7, 5))
plt.bar(sentiment_count.index, sentiment_count.values)
plt.title("Sentiment Distribution")
plt.xlabel("Sentiment")
plt.ylabel("Number of Reviews")
plt.tight_layout()
plt.show()

sentiment_percentage = data["sentiment"].value_counts(normalize=True) * 100

print(sentiment_percentage.round(2))

plt.figure(figsize=(7, 7))
plt.pie(
    sentiment_percentage.values,
    labels=sentiment_percentage.index,
    autopct="%1.1f%%"
)
plt.title("Sentiment Percentage")
plt.tight_layout()
plt.show()

rating_by_sentiment = data.groupby("sentiment")["rating"].mean()

print(rating_by_sentiment)

plt.figure(figsize=(7, 5))
plt.bar(rating_by_sentiment.index, rating_by_sentiment.values)
plt.title("Average Rating by Sentiment")
plt.xlabel("Sentiment")
plt.ylabel("Average Rating")
plt.tight_layout()
plt.show()

#brand wise
brand_sentiment = pd.crosstab(data["brand"], data["sentiment"])

print(brand_sentiment.head())

top_brands = data["brand"].value_counts().head(10).index

top_brand_data = data[data["brand"].isin(top_brands)]

brand_sentiment_top = pd.crosstab(
    top_brand_data["brand"],
    top_brand_data["sentiment"]
)

print(brand_sentiment_top)

brand_sentiment_top.plot(kind="bar", figsize=(12, 6))

plt.title("Sentiment Count by Top 10 Brands")
plt.xlabel("Brand")
plt.ylabel("Number of Reviews")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Which brands have highest positive reviews?
brand_positive = data.groupby("brand").agg(
    total_reviews=("review_text", "count"),
    positive_reviews=("sentiment", lambda x: (x == "Positive").sum()),
    negative_reviews=("sentiment", lambda x: (x == "Negative").sum()),
    neutral_reviews=("sentiment", lambda x: (x == "Neutral").sum())
)

brand_positive["positive_percentage"] = (
    brand_positive["positive_reviews"] / brand_positive["total_reviews"] * 100
)

brand_positive = brand_positive.sort_values("positive_percentage", ascending=False)

print(brand_positive.head(10))

top_positive_brands = brand_positive.head(10)

plt.figure(figsize=(10, 6))
plt.bar(top_positive_brands.index, top_positive_brands["positive_percentage"])
plt.title("Top 10 Brands by Positive Review Percentage")
plt.xlabel("Brand")
plt.ylabel("Positive Review Percentage")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Which brands have highest negative reviews?
brand_negative = data.groupby("brand").agg(
    total_reviews=("review_text", "count"),
    negative_reviews=("sentiment", lambda x: (x == "Negative").sum())
)

brand_negative["negative_percentage"] = (
    brand_negative["negative_reviews"] / brand_negative["total_reviews"] * 100
)

brand_negative = brand_negative.sort_values("negative_percentage", ascending=False)

print(brand_negative.head(10))

top_negative_brands = brand_negative.head(10)

plt.figure(figsize=(10, 6))
plt.bar(top_negative_brands.index, top_negative_brands["negative_percentage"])
plt.title("Top 10 Brands by Negative Review Percentage")
plt.xlabel("Brand")
plt.ylabel("Negative Review Percentage")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Clean review text
data["clean_review"] = (
    data["review_text"]
    .astype(str)
    .str.lower()
    .str.replace(r"[^a-zA-Z\s]", "", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

data[["review_text", "clean_review"]].head()

#Most common words in reviews
all_words = " ".join(data["clean_review"]).split()

stop_words = [
    "the", "is", "and", "a", "an", "to", "of", "for", "in", "on",
    "this", "that", "it", "with", "as", "was", "were", "be", "but",
    "not", "so", "very", "i", "my", "you", "are", "its", "at"
]

filtered_words = []

for word in all_words:
    if word not in stop_words and len(word) > 2:
        filtered_words.append(word)

word_count = pd.Series(filtered_words).value_counts().head(20)

print(word_count)

plt.figure(figsize=(12, 6))
plt.bar(word_count.index, word_count.values)
plt.title("Top 20 Most Common Words in Reviews")
plt.xlabel("Words")
plt.ylabel("Frequency")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Most common words in negative reviews
negative_reviews = data[data["sentiment"] == "Negative"]

negative_words = " ".join(negative_reviews["clean_review"]).split()

negative_filtered_words = []

for word in negative_words:
    if word not in stop_words and len(word) > 2:
        negative_filtered_words.append(word)

negative_word_count = pd.Series(negative_filtered_words).value_counts().head(20)

print(negative_word_count)

plt.figure(figsize=(12, 6))
plt.bar(negative_word_count.index, negative_word_count.values)
plt.title("Top 20 Common Words in Negative Reviews")
plt.xlabel("Words")
plt.ylabel("Frequency")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Most common words in positive reviews
positive_reviews = data[data["sentiment"] == "Positive"]

positive_words = " ".join(positive_reviews["clean_review"]).split()

positive_filtered_words = []

for word in positive_words:
    if word not in stop_words and len(word) > 2:
        positive_filtered_words.append(word)

positive_word_count = pd.Series(positive_filtered_words).value_counts().head(20)

print(positive_word_count)

plt.figure(figsize=(12, 6))
plt.bar(positive_word_count.index, positive_word_count.values)
plt.title("Top 20 Common Words in Positive Reviews")
plt.xlabel("Words")
plt.ylabel("Frequency")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Simple lexicon-based sentiment prediction
positive_words = [
    "good", "great", "excellent", "amazing", "best", "love", "loved",
    "awesome", "perfect", "fast", "smooth", "beautiful", "nice",
    "worth", "recommend", "durable", "solid", "satisfied"
]

negative_words = [
    "bad", "poor", "worst", "hate", "hated", "slow", "terrible",
    "awful", "waste", "problem", "issues", "issue", "disappointed",
    "overpriced", "lag", "heating", "broken", "weak", "not"
]

def predict_sentiment(text):
    words = str(text).lower().split()

    positive_score = 0
    negative_score = 0

    for word in words:
        if word in positive_words:
            positive_score = positive_score + 1
        elif word in negative_words:
            negative_score = negative_score + 1

    if positive_score > negative_score:
        return "Positive"
    elif negative_score > positive_score:
        return "Negative"
    else:
        return "Neutral"

data["predicted_sentiment"] = data["clean_review"].apply(predict_sentiment)

data[["review_text", "sentiment", "predicted_sentiment"]].head(10)

# predictiion accuracy
correct_predictions = data["sentiment"] == data["predicted_sentiment"]

accuracy = correct_predictions.mean() * 100

print("Accuracy:", round(accuracy, 2), "%")

confusion_table = pd.crosstab(
    data["sentiment"],
    data["predicted_sentiment"],
    rownames=["Actual Sentiment"],
    colnames=["Predicted Sentiment"]
)

print(confusion_table)

data.to_csv("Task4_Mobile_Sentiment_Analysis_Result.csv", index=False)

print("File saved successfully")